"""Dillon Agency: editable commercial website content.

Firm services and delivery live here. Keir's complete story and advisor resources
remain on his personal site. No client performance figures are invented.
"""
from components import page,pic,contact
PAGES=[]
def add(*args):PAGES.append(page(*args))
def close(title='Let’s talk about<br><em>your firm.</em>',text='Bring the priorities, the people involved, and the work you want to move forward.'):
    return '<section class="simple-close metal-surface"><h2>'+title+'</h2><div><p>'+text+'</p><a class="button" href="[[contact]]">Start a conversation</a></div></section>'
def opening(kicker,title,description):
    return '<section class="story-opening"><p class="kicker">'+kicker+'</p><h1>'+title+'</h1><div class="story-opening-bottom"><p>'+description+'</p><span>Dillon Agency<br>Led by Keir Dillon</span></div></section>'

add('home','/','Marketing leadership for wealth management firms','Dillon Agency, led by Keir Dillon, connects brand strategy, fractional CMO leadership, recruiting, and advisor marketing for wealth management firms.',
'''<section class="editorial-hero"><div class="hero-copy"><p class="kicker">Marketing leadership for wealth management firms</p><h1>Give your firm<br>a clear direction.<br><em>Then lead the work.</em></h1><p class="hero-intro">Dillon Agency connects brand strategy, marketing team leadership, recruiting, and advisor support. Led by Keir Dillon, with an active role in the work from direction through delivery.</p><a class="text-action" href="[[cmo]]">Explore fractional CMO leadership <span aria-hidden="true">↗</span></a><div class="hero-signature"><span class="signature">Dillon Agency</span><span>Founder-led. Personally involved.</span></div></div><div class="hero-image">'''+pic('advisors-hero','Illustrative scene of two financial professionals in a working conversation','hero-photo',eager=True)+'''<div class="image-foot"><span>For the firm and the people building it.</span><span class="accent-line" aria-hidden="true"></span></div></div></section>
<section class="intro-spread"><p class="margin-note">The leadership between the projects</p><div><h2>One business.<br>Many priorities.<br><em>A connected plan.</em></h2></div><div class="intro-copy"><p>The brand needs attention. Recruiting needs a clearer story. Advisors need marketing support. Your team needs to know what comes first.</p><p>We help connect those priorities to the firm’s goals, define the work, and lead it with the people responsible for delivery.</p><a class="text-action" href="[[approach]]">How the work comes together <span aria-hidden="true">↗</span></a></div></section>
<section class="tool-workbench metal-surface"><div class="section-heading"><div><p class="kicker">Where we work</p><h2>Direction that reaches<br><em>the day-to-day.</em></h2></div><p>A fractional CMO engagement can connect the full picture. A defined project can address a specific priority. Scope follows the firm’s needs and capacity.</p></div><div class="tool-list"><a class="tool-row" href="[[cmo]]"><h3>Fractional CMO</h3><p>Senior marketing leadership alongside your executive team.</p><span class="arrow">↗</span></a><a class="tool-row" href="[[brand]]"><h3>Brand &amp; recruiting strategy</h3><p>A clear position and a recruiting story grounded in the firm’s experience.</p><span class="arrow">↗</span></a><a class="tool-row" href="[[advisors]]"><h3>Advisor marketing support</h3><p>A practical way to help advisors clarify their brands and communicate.</p><span class="arrow">↗</span></a><a class="tool-row" href="[[systems]]"><h3>Marketing systems &amp; AI</h3><p>Workflows, ownership, and carefully scoped tools that support delivery.</p><span class="arrow">↗</span></a></div></section>
<section class="firm-record"><div class="firm-record-intro"><p class="kicker">Selected work / Coastal Wealth</p><h2>At the firm level.<br><em>Close to the advisor.</em></h2><p>Keir’s work at Coastal Wealth spans brand strategy, marketing team leadership, recruiting strategy and implementation, and individual advisor support.</p><p>It is a practical example of the responsibilities a CMO role can connect.</p><a class="text-action" href="[[coastal]]">Explore the scope of work <span aria-hidden="true">↗</span></a></div><dl class="scope-register"><div><dt>Direction</dt><dd>Connect brand and marketing priorities with leadership.</dd></div><div><dt>Delivery</dt><dd>Lead the team and help carry the strategy into implementation.</dd></div><div><dt>Advisor experience</dt><dd>Keep the firm’s recruiting and support work close to the people it serves.</dd></div></dl></section>
<section class="engagement-spread"><div><p class="kicker">The founder behind the firm</p><h2>Keir Dillon.<br><em>A builder’s perspective.</em></h2><p>Professional athlete, broadcaster, and co-founder and CEO of FRENDS. Keir brings experience building brands and companies into the work with financial services leaders.</p><a class="text-action" href="[[about]]">Meet the founder <span aria-hidden="true">↗</span></a></div><div><p class="kicker">A clear way to work together</p><h3>Keir leads the engagement.</h3><p>We define the responsibilities of your team, Dillon Agency, and any specialist partners around the agreed scope. The goal is clarity about who owns the decisions and who delivers the work.</p><p>Start with a conversation about the role or project your firm needs.</p></div></section>'''+close())

add('services','/services/','Services for wealth management firms','Explore Dillon Agency’s fractional CMO, brand and recruiting strategy, advisor marketing, and practical marketing systems services.',
opening('Services','Start with the need.<br><em>Define the right engagement.</em>','The firm’s priorities determine the scope. Senior leadership connects the work; focused projects give a specific decision or initiative the attention it needs.')+
'''<div class="service-index"><a href="[[cmo]]"><div><span class="kicker">Ongoing leadership</span><h2>Fractional CMO</h2></div><div><p>For a firm that needs someone to connect strategy, people, and delivery over time.</p><p>Executive alignment, marketing priorities, team leadership, implementation oversight, and a useful review rhythm.</p><span class="text-action">Explore the role ↗</span></div></a><a href="[[brand]]"><div><span class="kicker">A defined strategic priority</span><h2>Brand &amp;<br>recruiting strategy</h2></div><div><p>For a firm clarifying its position, evolving its identity, or improving how it explains the opportunity to advisors.</p><p>Audience research, message architecture, recruiting narrative, and a practical plan for putting the direction to work.</p><span class="text-action">Explore the work ↗</span></div></a><a href="[[advisors]]"><div><span class="kicker">Support across the firm</span><h2>Advisor marketing</h2></div><div><p>For leadership teams that want a more consistent way to help advisors communicate their value.</p><p>Positioning, presence, content support, review responsibilities, and a process the team can operate.</p><span class="text-action">Explore advisor support ↗</span></div></a><a href="[[systems]]"><div><span class="kicker">A better way to deliver</span><h2>Marketing systems<br>&amp; practical AI</h2></div><div><p>For teams improving a repeatable workflow or connecting tools to a clear operating process.</p><p>Workflow mapping, scoped pilots, human review, documentation, and measures tied to actual use.</p><span class="text-action">Explore the systems work ↗</span></div></a></div>'''+close(text='A first conversation helps distinguish a leadership need from a focused project and makes the next step concrete.'))

add('cmo','/fractional-cmo/','Fractional CMO for wealth management firms','Work with Keir Dillon through Dillon Agency for embedded marketing leadership across brand, recruiting, team direction, and advisor support.',
opening('Fractional CMO','Senior direction.<br><em>Ongoing responsibility.</em>','Keir works alongside your CEO and leadership team to set marketing priorities, lead the people delivering them, and stay involved as the strategy becomes execution.')+
'''<section class="engagement-spread"><div><h2>When the work needs<br><em>a leadership role.</em></h2><p>You have marketing activity and people doing the work. The unresolved questions sit between them: what matters most, how the pieces connect, and who owns the decisions.</p></div><div><h3>A role shaped around the firm</h3><p>The engagement can connect brand direction, recruiting, advisor marketing, team leadership, and marketing systems. Its scope is agreed around the business need and the resources available.</p><p>Keir is the senior lead. Your team and specialist partners participate with explicit responsibilities.</p></div></section>
<section class="approach-steps"><div class="step"><span class="step-label">Direction</span><h2>Make the priorities<br>clear and usable.</h2><div><p>Agree on the audiences, position, business priorities, and the marketing decisions needed to support them.</p><p>Typical working materials: a message framework, a focused roadmap, and decision criteria for the team.</p></div></div><div class="step"><span class="step-label">Leadership</span><h2>Help the team<br>carry the work forward.</h2><div><p>Set responsibilities, clarify briefs, coordinate partners, review work, and resolve the choices that slow delivery.</p><p>A proposed cadence begins with weekly working reviews and regular leadership decisions, adjusted to the engagement.</p></div></div><div class="step"><span class="step-label">Implementation</span><h2>Stay involved<br>as the plan meets reality.</h2><div><p>Connect the work across recruiting, brand presence, advisor support, content, and systems. Agree who produces, approves, publishes, and maintains each deliverable.</p><p>Implementation capacity is scoped explicitly, including any specialist delivery.</p></div></div><div class="step"><span class="step-label">Learning</span><h2>Make progress<br>something you can review.</h2><div><p>Define success measures with the firm, establish the starting evidence, and review outcomes alongside delivery progress.</p><p>Separate completed work, adoption, and business results so the conversation stays useful.</p></div></div></section>
<section class="brand-relationship metal-surface"><div><h2>Agree on the role.<br><em>Then get to work.</em></h2></div><div><p>Before starting, we define priorities, decision authority, time commitment, internal and external responsibilities, review cadence, fees, and what falls outside scope.</p><p>The engagement is tailored. No package price or fixed team capacity is assumed before that conversation.</p><a class="text-action" href="[[coastal]]">See Keir’s current scope at Coastal Wealth <span aria-hidden="true">↗</span></a></div></section>'''+close())

add('brand','/brand-strategy/','Brand and advisor recruiting strategy','Dillon Agency helps wealth management firms clarify their position, develop a credible recruiting narrative, and carry the message into the experience.',
opening('Brand & recruiting strategy','A firm worth choosing.<br><em>A reason people understand.</em>','Clarify the firm’s position and connect the recruiting story to the experience an advisor can actually expect.')+
'''<section class="engagement-spread"><div><h2>Start with<br><em>the choices behind the words.</em></h2><p>Who is the firm built to support? What work does it do especially well? Where does the advisor experience support that claim? Those decisions give the message something real to stand on.</p></div><div><h3>Listen before writing</h3><p>Review current materials and speak with leadership, recruiting, and advisors as the scope allows. Understand actual alternatives, expectations, friction, and reasons people stay.</p><p>Use those observations to distinguish established strengths from promises the firm is still working to deliver.</p></div></section>
<section class="approach-steps"><div class="step"><span class="step-label">Position</span><h2>Choose the audience<br>and the relevant difference.</h2><div><p>Develop a position that reflects the firm’s capabilities and intended direction. Define the supporting evidence and the language each audience can understand.</p></div></div><div class="step"><span class="step-label">Expression</span><h2>Carry the idea<br>across the experience.</h2><div><p>Translate the position into messages, creative direction, website priorities, recruiting materials, and conversations. Agree what needs to change and who will implement it.</p></div></div><div class="step"><span class="step-label">Recruiting</span><h2>Make the promise<br>specific enough to assess.</h2><div><p>Connect the recruiting narrative with the advisor’s journey, the questions they ask, and the support the firm provides. Plan the materials and handoffs needed to carry that story through.</p></div></div></section>
<section class="deliverable-register metal-surface"><h2>What the work can produce</h2><dl><div><dt>A clear position</dt><dd>Audience choices, a relevant promise, and supporting evidence.</dd></div><div><dt>A message framework</dt><dd>Firm narrative, advisor value, and language for key conversations.</dd></div><div><dt>A direction for expression</dt><dd>Priorities for the website, identity, content, and recruiting materials.</dd></div><div><dt>An implementation plan</dt><dd>Owners, sequence, review responsibilities, and a way to learn from use.</dd></div></dl></section>'''+close())

add('advisors','/advisor-marketing/','Advisor marketing support for wealth management firms','Build a practical advisor marketing support model with Dillon Agency: positioning, presence, content, review workflows, and firm-level ownership.',
opening('Advisor marketing support','Make useful support<br><em>part of the advisor experience.</em>','Help individual advisors communicate clearly through a process the firm can sustain.')+
pic('advisor-community','Illustrative scene of financial professionals discussing ideas around a table','community-photo','Illustrative working scene; not a photograph of a client engagement.',True)+
'''<section class="room-body"><div><h2>Start with the advisor.<br><em>Design the support around the work.</em></h2><p>Advisors need help making choices: whom they serve, how to explain their value, what their public presence says, and which questions deserve a useful answer.</p><p>The firm needs a way to deliver that support with clear ownership, reasonable capacity, and its normal review process.</p></div><div class="room-agenda"><h3>The work to connect</h3><p>Client focus and positioning</p><p>Website and profile clarity</p><p>A workable content routine</p><p>Review and implementation support</p></div></section>
<section class="engagement-spread"><div><h2>A pilot gives the firm<br><em>something concrete to learn from.</em></h2><p>Begin with an agreed group of advisors and a clearly defined need. Document what support is offered, how the work moves, and who is responsible at each stage.</p></div><div><h3>Build from actual use</h3><p>Review completion, clarity, time required, rework, and advisor feedback. Use what you learn to refine the service before expanding it.</p><p>This is a proposed approach to an engagement, not a report of completed pilot results.</p></div></section>
<section class="brand-relationship metal-surface"><div><p class="kicker">A practical starting point</p><h2>Try the thinking<br><em>through Keir’s resources.</em></h2></div><div><p>Keir’s personal site hosts the Positioning Blueprint quick start, The Sniff Test, and the client-question planner. They are available at no cost and without registration.</p><p>The tools help an individual make progress. A firm engagement defines how support is delivered and maintained across the organization.</p><a class="text-action" href="{{peer:/tools/}}">Open Keir’s advisor resources <span aria-hidden="true">↗</span></a></div></section>'''+close())

add('systems','/marketing-systems/','Marketing systems and practical AI workflows','Dillon Agency helps marketing teams map responsibilities, scope AI workflow pilots, retain human review, and assess results against actual delivery needs.',
opening('Marketing systems & practical AI','Improve the workflow.<br><em>Keep ownership clear.</em>','Connect tools to a defined task, a named owner, and a result the team can evaluate.')+
'''<section class="engagement-spread"><div><h2>Begin with<br><em>the work that repeats.</em></h2><p>Before adding technology, look at how the work moves today. Where does information arrive? Who prepares it? Who checks it? What needs approval? What happens after publication?</p></div><div><h3>A bounded place to start</h3><p>Examples include organizing an advisor interview into a draft brief, preparing research for a content discussion, or making the review handoff clearer.</p><p>Choose the task around the firm’s permitted tools, data practices, team capacity, and review responsibilities.</p></div></section>
<section class="workflow-sheet metal-surface"><p class="kicker">Illustrative workflow / Advisor content</p><h2>From a conversation<br><em>to material the team can use.</em></h2><ol><li><h3>Capture the source</h3><p>Use approved material and identify the question the content should answer.</p></li><li><h3>Prepare a draft brief</h3><p>Organize the material into a bounded draft. Keep its source and assumptions visible.</p></li><li><h3>Review with accountable people</h3><p>Check accuracy, voice, context, and the firm’s required approvals.</p></li><li><h3>Publish and learn</h3><p>Use the approved channel, retain the agreed record, and review actual use.</p></li></ol><p class="note">This illustrates an approach. It does not represent a measured client deployment or an installed software product.</p></section>
<section class="engagement-spread"><div><h2>Define success<br><em>before the pilot.</em></h2><p>Agree how to compare the proposed workflow with the current one. Useful measures may include preparation time, rework, output quality, review completion, and actual adoption.</p></div><div><h3>Leave the team with a usable process</h3><p>A scoped engagement can produce a workflow map, roles, a pilot configuration, review criteria, and operating documentation.</p><p>Specific integrations, software costs, permissions, and ongoing maintenance are agreed before implementation.</p></div></section>'''+close())

add('approach','/approach/','How Dillon Agency works with firms','A clear engagement approach: understand the firm, agree priorities and responsibilities, lead delivery, and review evidence with leadership.',
'''<section class="approach-opening"><div><p class="kicker">How we work</p><h1>Inside the priorities.<br><em>Accountable for<br>the next step.</em></h1><p class="intro">A close working relationship with the firm’s leadership and the people carrying the work forward.</p><p>We begin by understanding the business, agree on a useful scope, and establish how decisions and delivery will work.</p></div>'''+pic('advisor-walking','Illustrative portrait of a financial professional outside an office','approach-portrait',eager=True)+'''</section>
<section class="approach-steps"><div class="step"><span class="step-label">Understand</span><h2>Start with the business<br>you are actually building.</h2><div><p>Listen to leadership and the relevant team. Review current work, audience assumptions, resources, and where progress is getting stuck.</p><p>Working output: a shared view of the problem, constraints, and decisions needed.</p></div></div><div class="step"><span class="step-label">Agree</span><h2>Turn priorities<br>into a defined commitment.</h2><div><p>Choose the scope and sequence. Establish decision authority, deliverables, responsibilities, cadence, fees, and success measures.</p><p>Working output: an engagement brief and a practical delivery plan.</p></div></div><div class="step"><span class="step-label">Lead &amp; deliver</span><h2>Keep the work<br>connected to the direction.</h2><div><p>Work with the team, coordinate specialist support, review the material, and resolve decisions. Keep leadership informed about progress and choices that need attention.</p><p>Working output: useful deliverables and a visible record of ownership and progress.</p></div></div><div class="step"><span class="step-label">Review &amp; improve</span><h2>Learn from what<br>gets used and what changes.</h2><div><p>Review delivery, adoption, and the agreed business measures. Refine the work, document what the team needs, and agree the next priorities.</p><p>Working output: a clear view of what happened, what remains uncertain, and what comes next.</p></div></div></section>
<section class="brand-relationship metal-surface"><div><h2>A clear owner<br><em>for every part.</em></h2></div><div><p>Keir leads strategy and the senior marketing relationship. Your team brings business knowledge and agreed implementation capacity. Dillon Agency and specialist partners contribute the work defined in scope.</p><p>We agree who creates, who approves, who publishes, and who maintains the result. Partner involvement is based on the engagement; a fixed in-house team is not implied.</p></div></section>'''+close())

add('work','/selected-work/','Selected work | Dillon Agency','Explore the scope of Keir Dillon’s marketing leadership at Coastal Wealth and the responsibilities connecting firm strategy with advisor support.',
opening('Selected work','The scope behind<br><em>the relationship.</em>','A view into current firm work and the responsibilities that connect strategy to delivery.')+
'''<section class="firm-record"><div class="firm-record-intro"><p class="kicker">Coastal Wealth</p><h2>Firm-level leadership.<br><em>Advisor-level relevance.</em></h2><p>Keir’s responsibilities connect brand strategy, marketing team leadership, recruiting strategy and implementation, and support for individual advisors.</p><a class="text-action" href="[[coastal]]">Explore the engagement scope <span aria-hidden="true">↗</span></a></div><dl class="scope-register"><div><dt>Leadership</dt><dd>Brand direction and marketing priorities with the firm.</dd></div><div><dt>Implementation</dt><dd>Team leadership and coordination across the work.</dd></div><div><dt>Support</dt><dd>Recruiting strategy and individual advisor marketing.</dd></div></dl></section>
<section class="advisor-bridge"><h2>The experience<br><em>behind the approach.</em></h2><div><p>Keir also brings founder experience from FRENDS and OPEN. Those chapters inform his judgment; they are presented as his prior company-building experience.</p><a class="text-action" href="{{peer:/about/}}">Explore Keir’s full story <span aria-hidden="true">↗</span></a></div></section>'''+close())

add('coastal','/selected-work/coastal-wealth/','Coastal Wealth | Marketing leadership scope','Keir Dillon’s current Coastal Wealth scope: brand strategy, marketing team leadership, recruiting strategy and implementation, and advisor marketing support.',
opening('Selected work / Coastal Wealth','Leadership at the firm.<br><em>Support close to the advisor.</em>','An overview of Keir’s responsibilities, connecting the firm’s brand direction with the team, recruiting work, and individual advisor marketing.')+
'''<section class="engagement-spread"><div><p class="kicker">The context</p><h2>Connected responsibilities<br><em>across the firm.</em></h2><p>A firm’s brand, recruiting narrative, marketing team, and advisor support influence one another. This role brings those responsibilities into a shared leadership conversation.</p></div><div><p class="kicker">Keir’s role</p><h3>Strategy, team leadership, and implementation.</h3><p>At Coastal Wealth, Keir works with leadership on high-level brand strategy, leads the marketing team, helps drive recruiting strategy and implementation, and works with individual advisors on their marketing.</p><p>The focus is on connecting the decisions with the people responsible for carrying them forward.</p></div></section>
<section class="deliverable-register metal-surface"><h2>The scope of the work</h2><dl><div><dt>Firm brand strategy</dt><dd>Help shape the position and message with leadership, then connect that direction to marketing decisions.</dd></div><div><dt>Marketing team leadership</dt><dd>Guide the people doing the work and coordinate implementation across priorities.</dd></div><div><dt>Advisor recruiting</dt><dd>Help develop the strategy and carry it into the recruiting experience.</dd></div><div><dt>Individual advisor marketing</dt><dd>Help advisors translate their focus into their brand, message, and presence.</dd></div></dl></section>
<section class="engagement-spread"><div><h2>What another firm<br><em>can take from the role.</em></h2><p>You may already have staff, agencies, and technology. A senior marketing role can connect their work to the business direction and lead the decisions between them.</p></div><div><h3>Start with the relationship between priorities.</h3><p>What should the firm be known for? What does the recruiting story promise? What support do advisors experience? Who turns those answers into a usable plan for the team?</p><p class="note">This page describes responsibilities. It is not a client testimonial or a report of measured recruiting, revenue, or AI implementation results.</p></div></section>'''+close())

add('about','/about/','About Dillon Agency | Led by Keir Dillon','Dillon Agency is led by Keir Dillon, a founder and fractional CMO bringing brand strategy and implementation leadership to wealth management firms.',
opening('About Dillon Agency','Founder-led thinking.<br><em>Personally involved delivery.</em>','Dillon Agency is the business through which Keir Dillon works with firm leaders on brand strategy, marketing leadership, recruiting, and advisor support.')+
'''<section class="today-chapter"><div>'''+pic('keir-current','Keir Dillon, founder of Dillon Agency','today-portrait','Keir Dillon / Founder')+'''</div><div class="chapter-copy"><p class="kicker">The founder</p><h2>A builder’s perspective<br><em>on the firm.</em></h2><p>Keir’s background includes professional snowboarding, live broadcasting with ESPN and Fuel TV, and building consumer brands.</p><p>As co-founder and CEO of FRENDS, he worked across brand, product, team, and retail relationships. With OPEN, he explored how art and community could shape a different expression of beer culture.</p><p>Today, he brings those experiences into fractional CMO work in financial services.</p><a class="text-action" href="{{peer:/about/}}">Read the full story on Keir’s site <span aria-hidden="true">↗</span></a></div></section>
<section class="founder-archive-pair"><div>'''+pic('frends-product','Iridescent FRENDS headphones from Keir’s founder archive','agency-product','FRENDS / Keir’s prior founder experience')+'''</div><div>'''+pic('open-cans','OPEN beer cans with art-led packaging','agency-product','OPEN / Keir’s prior founder experience')+'''</div></section>
<section class="engagement-spread"><div><h2>A focused relationship.<br><em>A clearly scoped team.</em></h2><p>Keir leads the engagement. The delivery model is shaped around the firm’s team and the specialist support the work requires.</p></div><div><h3>Make the responsibilities explicit.</h3><p>Before beginning, we agree on leadership, production, approvals, implementation, and maintenance. Where outside partners are needed, their role and scope are defined.</p><p>The aim is a working relationship the firm can understand and a plan the people involved can carry out.</p></div></section>
<section class="brand-relationship metal-surface"><div><h2>The person.<br><em>The practice.</em></h2></div><div><p>KeirDillon.com hosts Keir’s writing, career story, Google Yourself, and practical advisor resources. Dillon Agency is the home for firm services, engagement details, and commercial work.</p><a class="text-action" href="{{peer:/}}">Visit Keir’s personal site <span aria-hidden="true">↗</span></a></div></section>'''+close())

add('contact','/contact/','Contact Dillon Agency','Contact Keir Dillon at Dillon Agency to discuss fractional CMO leadership, brand strategy, recruiting, advisor marketing, or a defined project.',contact('Dillon Agency','Dillon Agency: a conversation about our firm'))
